version: '3.4'

services:
  db:
    image: "postgres:12"
    hostname: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  usdafnsingest:
    image: usdafnsingest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/src

volumes:
  postgres-data:
